### ISSUE TITLE
Ex Nilio Creatio Stone Rod / Stone Axle not craftable

### ISSUE THREAD

**Issue by Sataana** [FTBTeam/FTB-Presents-Stoneblock-2#103]
* **Modpack Version**: 1.1.0 and up

* **Issue**: Ex Nihilo Creatio; Stone Rods not craftable to make Stone Axle. Refuses to accept Tinkers Stone Rods

* **Is it Repeatable?**: Yup, try crafting it.

* **Known Fix**: Ether change the recipe to use Tinkers Stone Rods, or put Ex Nihilo Creatio stone rods back in the game.
![image](https://user-images.githubusercontent.com/8507489/51034031-36814100-159d-11e9-9590-687ec78db6c5.png)

**Comment by Sunekaer** [comment]
Ty will change the recipe in the mean time use the "Forge Lexicon" to change them to the ex nihilo version

**Comment by Sataana** [comment]
Okay, so tried it both with the book and the block, nether will actually allow it.

![image](https://user-images.githubusercontent.com/8507489/51076530-8e996f80-1691-11e9-9986-ad25110c8ab7.png)

**Comment by Sunekaer** [comment]
no change mod not to block press v while having it hand

**Comment by Sataana** [comment]
Yeah no, it just doesn't work, I am able to do it with other items, not with the Stone Rods

**Comment by Iomega0318** [comment]
Correct, this is not transmutable because the item is "disabled" in the scripts.
At least and not being a modder that is my best guess, but yes we cannot transmute or convert them in any way.

//removing Stone Rod favouriting tinkers Stone Rod
mods.jei.JEI.removeAndHide(<exnihilocreatio:item_material:6>);

**Comment by thevipe** [comment]
The issue is present as the rod to be created is 3 cobble/stone diagonally is hidden/removed i also tried to use the "Forge Lexicon" to transmute and it didn't work same with the "Lexical Transmuter" to transmute it to the other rod!

Reference: https://teamcofh.com/docs/thermal-foundation/forge-lexicon/

since its disabled its not coming up and this is what the lexicon transmuter is supposed to do (https://youtu.be/FORKPAXfs-E?t=644) but it isn't working at all for some odd reason for me either might create a different issue for this tho
