### ISSUE TITLE
Game crash with I believe Avaritia and JEI again. 

### ISSUE THREAD

**Issue by ttechr** [FTBTeam/FTB-Presents-Stoneblock-2#153]
* **Modpack Version**: 1.0.1

* **Issue**: When going into my inventory by pressing E I get an immediate "not responding" as you can see from the video linked, I can go into other items that shows my inventory and those work fine. I have tried updated JEI to see if that fixes it but no luck.   https://youtu.be/8UpeelpJiO0

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/23390963

* **Is it Repeatable?**: Well every time I reload the game and get back in it still does it. 

* **Mod/s Affected**: I am thinking JEI and Avaritia

* **Known Fix**: unknown

**Comment by Sunekaer** [comment]
well, i cant recreate this, i dont see anything the log

**Comment by Sunekaer** [comment]
I dont really know if its JEI doing that, you can try and update it and see if it fixes it

**Comment by WindFox** [comment]
It might actually be your GPU. I can't play ANY pack with Avaritia on my laptop due to it's GPU (Nvidia Quadro K1000M). I get this exact problem (granted I never tried testing a world that already has items in inventories.) I can get it to happen in creative when I go to the Avarita tab without JEI installed.

(Just throwing my experience in here)

**Comment by ttechr** [comment]
After messing around with my inventory I got it to work. No clue what exactly is causing it though.
