### ISSUE TITLE
flux rifts are not spawning 

### ISSUE THREAD

**Issue by supernick02** [FTBTeam/FTB-Presents-Stoneblock-2#177]
* **Modpack Version**: 1.1.1 and maybe 1.2.0

* **Issue**: flux rifts from thaumcraft are not spawning

* **Is it Repeatable?**: yes

* **Mod/s Affected**: thaumcraft

**Comment by iKurama** [comment]
Can confirm. Dropped several stacks of quibit cells into a cauldron and got way above 32k flux (With about 152 vis), without dropping one bit of taint or getting a rift.

**Comment by ChromeFlux** [comment]
Is Wuss Mode on by default in this pack?

**Comment by ukdyl94** [comment]
Wuss Mode is enabled by default.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by Sunekaer** [comment]
I know is doenst spawn, but you shouldnt need it, we changed the recipes for the things we found in testing that needed it

**Comment by ChromeFlux** [comment]
@Sunekaer So How do I advance into the Flux Cleanup from the Flux "Let the Flux Build" Stage?

**Comment by Sunekaer** [comment]
Not every resource is able to be done in this world type thats why the "Crimson Rites" quest gives you all the research your missing

**Comment by ChromeFlux** [comment]
Ok, sounds like a plan. Thanks. The only reason I asked was because there was a bit of confusion a couple days ago in a thread related to visiting the nether where there was a tip here -https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/92

to read the description of the "flux filter" quest in order to get a tip on how to get to the nether (through the use of the terraformer from extra utils 2) I had thought the "flux filter" quest you were talking about was the one after the Flux research in the Fundamentals tab. But now that I think about it, You were probably meaning the Improved Essentia Distillation (part 2) right? If either of those are the case then the progress is naturally halted, if its part of the Flux research then flux rifts don't spawn we're left confused, and if its the improved essentia distillation, which can only be researched after we visit the nether, then the tip is in the wrong place. Where exactly is this tip? I know the issue is closed and feel free to ignore me, I don't need an answer. I'm sure you're busy making the pack super great, thanks for all you do!

**Comment by boris11221** [comment]
I have a question, if there are no rifts how am i supposed to get primordial pearls?
