### ISSUE TITLE
Server island commands are gone or renamed

### ISSUE THREAD

**Issue by ArbitraryHubris** [FTBTeam/FTB-Presents-Stoneblock-2#2]
* **Modpack Version**: 1.0.0

* **Issue**: when starting a server (with the server files), each new player is deposited at 0, 0 instead of getting their own island.  The old original stoneblock used void island control commands to /island leave, etc.  Those commands are not present in stoneblock 2, though the void island control mod is.

**Comment by Electrofried** [comment]
some silly person decided to change the configs to use /cave instead of /island breaking the mods documentation. Hopefully this can get changed back to use /island by default in the next update otherwise many people will keep reporting issues to the mod dev.
Easy enough to change it back to /island in the config (scroll down in the void island config to the command section.)

**Comment by ArbitraryHubris** [comment]
Many thanks, @Electrofried!

**Comment by ArbitraryHubris** [comment]
That still leaves the bug that users are not automatically given an island.  I tried setting autoCreate=true, but had strange results.  One player ended up at 0, 90, 0 and another was above the world which then put him in another dimension.  We'll continue to experiment.

**Comment by Sunekaer** [comment]
Yes command is /cave and you can enable auto create in void island control setting for you server

**Comment by ArbitraryHubris** [comment]
@Sunekaer I strongly encourage you to either change the command back to /island or put instructions in the pack description.  This is a discouraging initial experience.  

Also, autoCreate should be true by default.  

Both will help new server admins have a successful go with this new iteration.

**Comment by jikuja** [comment]
> otherwise many people will keep reporting issues to the mod dev.

Mod developer added an option to configure command name. Should pack authors stop using mod features just to decrease amount of bug reports sent to mod authors?

**Comment by rhaejr** [comment]
In this case, the Mod author should document this better because we searched the mod page for at least an hour trying to figure out why the mod wasn't working as intended. Also, pack devs should, and in this case have after this and another issue was brought up, make these changes from default known. Instead of not documenting changes from the norm.

**Comment by aaronhowser1** [comment]
It's in the pack description now
![image](https://user-images.githubusercontent.com/15698722/50715719-25d44680-1044-11e9-83cb-378aecfd02f0.png)

**Comment by rhaejr** [comment]
That is what I said about "in this case have [documented] after this and another issue was brought up"
