### ISSUE TITLE
[1.6.0]Servers crash

### ISSUE THREAD

**Issue by lzh1104** [FTBTeam/FTB-Presents-Stoneblock-2#337]
* **Modpack Version**: 1.6.0

* **Issue**: Servers occasionally crash after building the Brush Tower

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/3c456767

* **Is it Repeatable?**:  yes

* **Mod/s Affected**: thaumcraft

**Comment by nzminecraftDOTcom** [comment]
Looks like you have a ticking entity: Do this
To remove erroring entities (Mobs - skeletons etc) and tile entities (Pistons, crafting tables, interactive blocks...)

Close out of your game completely.

Do a world/save backup before proceeding.

 

Go to the config folder for the modpack, look for Forge.cfg

 

Find the lines 

 

# Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.

 

SET THIS PART TO TRUE:


B:removeErroringEntities=true

 

AND

 

# Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.

 

SET THIS PART TO TRUE


B:removeErroringTileEntities=true

 

 

Now start your game and load the world. If all went well it should load just fine. You should now try to do what you were doing when the crash occured. If that succeeds. Stop your game, and reset both those settings back to false. If you have issues further on, you can try leaving them on true but heed the warnings they state in their description.

**Comment by Sunekaer** [comment]
Answered by nzminecraft
