### ISSUE TITLE
Grave Keybind Conflict between Ore Excavation and Morph

### ISSUE THREAD

**Issue by Dragnier** [FTBTeam/FTB-Presents-Stoneblock-2#36]
* **Modpack Version**: 1.0.1

* **Issue**: The grave keybind for Morph does not show up in the regular Minecraft controls menu. This conflicts with Ore Excavation by default. The Morph controls are also not set by the Default Config mod. You have to go through Mod Options to Morph and config the key there. Took me forever to find though.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Morph, Ore Excavation

* **Known Fix**: The default control for Morph should be changed to another key before the pack is released. I am also going to post an issue for Morph... The keys should be registered to the controls menu properly by that mod author. But for now, making sure the default keybind is set properly should work.

**Comment by Sunekaer** [comment]
Just change the for morph, open options -> control and in the bottom right corner there a button/white text to click on to enter the keybinds

**Comment by Dragnier** [comment]
There is _not_ any link between Morph options and the Options -> Controls menu. This will be remedied in the future, but not for 1.12.2 and should be taken into consideration for default configuration of modpacks; especially when mod control conflicts arise between a relatively high use mod like Ore Excavation and one that is not as used. Many newer players who have no experience with iChun's alternate configuration menu specifically for their mods are going to be very frustrated by this. I've already seen at least one streamer who complained about this in a video and did not know about the other config.

You are already shipping custom config files with your modpack. All it would take is a single tweak on your end to eliminate lots of frustration for end-users. I honestly do not see the reason for not doing this since it would take you about 30 seconds extra before your next version update...

Referencing the issue on iChun Util github: https://github.com/iChun/iChunUtil/issues/184#issuecomment-451735294

**Comment by LemonZawodowiec** [comment]
Can this be pinned to the "Top" or "Front page" of issues? i almost wrote the same issue as New before checking if someone wrote this blatant thing before me -_-

**Comment by Dragnier** [comment]
@LemonZawodowiec They closed this already without fixing it.

**Comment by Thunder-Nova** [comment]
@Dragnier 
**Just so people know** (Since I have just replayed the game and found the same issue)

To change the key controls of Morph. (**It works while in-game so no worries**)

1. Open the menu
2. Mod Options...
3. Click on **Morph**
4. Config

You'll get the **not so smart by the developer** controls.

**Comment by Dragnier** [comment]
@Thunder-Nova 
Completely aware of that. The thing is, this could have had default key configs shipped with it easily that would have avoided the conflict. (Technically, all modpacks can do that...)

Also, that little comment about "not so smart by the developer" is not true. They did their own control system because it allows you to use any modifier key combination, not just one. So instead of just Ctrl + F for instance, you could do Ctrl + Alt + F if you wanted. Minecraft does not allow multiple keybind modifiers by default. So it is actually the Minecraft devs that should take the hint from iChun.

**Comment by Thunder-Nova** [comment]
@Dragnier 
ok, thought, I did say the "not so smart" in terms of searching for the keys to avoid conflict. Such as the morph and excavation. But **I do love how it is set-up, what I don't like it actually separate the keys**. Imagine if not only ichun did that, and multiple others did it too. It will create a very much conflicting problem (we can change the keys options but can't change our actual keyboards). It is way easier for modpack developers to have all the keys at one spot.

So I just added ALT to my morph keybind: "Alt-`" Since _I know_ there isn't one using that key setup.

The reason I commented is that it was the 1st thing it pop up in my google search, with no answer. So I had to see where it could be while in-game, which I recall the **mod options** which it does make me cringe when it comes to keybinding.
