### ISSUE TITLE
Partial World Reset

### ISSUE THREAD

**Issue by DeDeDespaDio** [FTBTeam/FTB-Presents-Stoneblock-2#42]
* **Modpack Version**:1.0.1

* **Issue**: I logged into my game today to find all my items that i had in chests on the floor, all of my blocks that i placed on the wall have dissappeared, but every area other than where the main room was are normal, but the main room was reset back to default.

* **Is it Repeatable?**: No

**Comment by Sunekaer** [comment]
was this in single player or on a server?

**Comment by mmarquezs** [comment]
Yup same, I have  a server,  when I connect the spawn hole where you initial appear it recreates again. For example the rooms next to it are not affected i can break the wall and they are fine.

**Comment by Sunekaer** [comment]
Are the server running Sponge?

**Comment by DeDeDespaDio** [comment]
> 
> 
> was this in single player or on a server?

single player

> 
> 
> Yup same, I have a server, when I connect, the spawn hole where you initial appear it recreates again. For example the rooms next to it are not affected i can break the wall and they are fine.

same with me

**Comment by mmarquezs** [comment]
> 
> 
> Okay are you playing at 0, 90, 0 or did you do /cave create to get on another place?
> 
> @mmarquezs is it spawn or your cave there does it?

I can't check it now, my server is being tested for hardware problems. I didn't use /cave create (maybe that's the problem?) I connected and I appeared in a hole and I started playing, so I'm guessing it's 0,90,0 if that's the spawn.

**Comment by DeDeDespaDio** [comment]
I was playing at 0/90/0

**Comment by prouderthings** [comment]
Also experiencing this issue on a multiplayer server (4 players) and it keeps happening more frequently,  Even in the mining dimension.  We can completely change an entire base (like a massive expansion) and leave the area for an hour (visiting another base 1000 blocks away), come back and the chunks have reverted back to what it was like days ago, including inventory in chest.  It's localized to only a few chunks, but it can happen anywhere.  What really puzzles me is how it reverts to a state that was over 24hrs prior and we have played a lot since then. We have not been able to find anything in the logs to indicate what is happening.  Progression is mute until we figure it out because everything we do has a high change of reverting. I'm certain is has to do with unloading chunks (when players leaves) and loading chunks back in (when a player returns).
