### ISSUE TITLE
Black Quartz Ore and the Grindstone

### ISSUE THREAD

**Issue by Copperearth** [FTBTeam/FTB-Presents-Stoneblock-2#59]
* **Modpack Version**: 1.0.1

* **Issue**: Black Quartz Ore from Actually Additions doesnt work in the Quartz Grindstone from AE2

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Actually Additions, Applied Energistics 2

**Comment by Boomflex** [comment]
This can be fixed by adding "QuartzBlack" to the grindstone part of the config.

I have uploaded a version to Pastebin that adds QuartzBlack to line 340 and it works.

https://pastebin.com/ZggWTDCD

![image](https://user-images.githubusercontent.com/22868795/50827432-56fb9200-1336-11e9-9ecc-211e6ae702db.png)

**Comment by Sunekaer** [comment]
1.1.0
