### ISSUE TITLE
Stoneblock 2 1.1.0 - reconsider backpack removal and disable for quest rewards/crafting without removing mod?

### ISSUE THREAD

**Issue by Electrofried** [FTBTeam/FTB-Presents-Stoneblock-2#83]
1.1.0

Ironbackpacks is the most used self storage mods for players due to the quest reward for diamond backpacks being a fairly common reward, removing a mod like this is going to cause major issues for servers and solo players. 

With this pack being released as 'stable' major mod changes/removals should have happened in beta. If you proceed to release 1.1.0, would it be possible to have the mod left included with the pack, at least for a few versions with a big bold warning up front that you plan to remove a  major storage mod from the pack in the patch notes and just disable the crafting/quest rewards for those items in the meantime?

**Comment by Boomflex** [comment]
As someone who just had to revert back to 1.0.1 due to losing A LOT of items in my Iron Backpack, I would most definitely ask you to reconsider.

Removing this mod because of potential dupes causes more headaches than people who just want to dupe and ruin it for themselves.

I have no issue sticking with 1.0.1 if need be but hoping you revert back the change here.

**Comment by Sunekaer** [comment]
1.1.1
